# Install with `cargo install just`
# Usage: `just --dotenv-filename /path/to/file.env <bench|gpu-bench> <args>`
# TODO: Move dotenv-filename into justfile once the feature is available
set dotenv-load

commit := `git rev-parse --short HEAD`

# Run CUDA benchmarks on GPU
bench +benches:
  #!/bin/sh
  #export LURK_RC=100,600
  for bench in {{benches}}; do
    cargo criterion --bench $bench --message-format=json 2>&1 > $bench-{{commit}}.json
  done

# Run CUDA benchmarks on GPU
gpu-bench-ci +benches:
  #!/bin/sh
  sudo apt-get update && sudo apt-get install pkg-config libfontconfig1-dev libfontconfig -y
  for bench in {{benches}}; do
    cargo criterion --bench $bench --message-format=json > $bench-{{commit}}.json
  done
