name: GPU benchmark on `main`
on:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: Bench and deploy
    runs-on: ubuntu-latest
    steps:
      # Install deps
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.22.0
      # Run benchmarks and deploy
      - name: Get old benchmarks
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Install criterion
        run: cargo install cargo-criterion
      - name: Copy old benchmarks locally for comparison
        run: |
          mkdir -p target gh-pages/benchmarks/criterion
          cp -r gh-pages/benchmarks/criterion target
      - name: Set env vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" | tee -a $GITHUB_ENV
          echo "LURK_BENCH_OUTPUT=gh-pages" | tee -a $GITHUB_ENV
          echo "LURK_RC=100,600" | tee -a $GITHUB_ENV
      # TODO: Check env vars work
      - name: Run benchmarks
        run: |
          just bench fibonacci
          mv fibonacci-${{ env.SHORT_SHA }}.json ..
        working-directory: ${{ github.workspace }}/benches
      - name: Check for existing plot data
        run: |
          if [ ! -f "plot-data.json" ]; then
            cat gh-pages/benchmarks/history/*.tar.gz | tar -xvzf - -i
          fi
        continue-on-error: true
      # If no plot data found, unzip all historical bench results and re-create the plots
      - name: Generate historical performance plot
        run: |
          cargo run
      # TODO: Prettify labels for easier viewing
      # Compress the benchmark file and metadata for later analysis
      - name: Compress artifacts
        run: |
          mkdir -p history
          echo $LABELS > labels.md
          tar -cvzf fibonacci-${{ env.SHORT_SHA }}.tar.gz Cargo.lock fibonacci-${{ env.SHORT_SHA }}.json labels.md
          cp fibonacci-${{ env.SHORT_SHA }}.tar.gz history
        working-directory: ${{ github.workspace }}
        # TODO: Make links at each level of Lurk website so we can navigate without the raw URL
      - name: Prepare HTML pages
        run: |
          if [[ ! -f plots.html ]]; then
            html=$(cat << EOF
          <!DOCTYPE html>
          <html>
          <head>
          <style>
          img {
            width: 100%;
          }
          </style>
          </head>
          <body>
          </body>
          </html>
          EOF
          )
            echo "$html" > plots.html
          fi

          shopt -s nullglob  # Prevent errors if no matching files are found

          for FILE in `ls *.png | sort -g`; do
             if [[ -f $FILE ]]; then # Check if it's a regular file
                 IMAGE="<img src=\"$FILE\" alt=\"Benchmark history plot for $FILE\" style=\"width:500px;height:500px;\"/>"
                 echo $IMAGE
                 sed -i "/<\/body>/i\\$IMAGE" plots.html
             fi
          done

          cp *.png plots.html history
      - name: Deploy latest benchmark report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion
          destination_dir: benchmarks/criterion
      - name: Deploy benchmark history
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./history
          destination_dir: benchmarks/history
          keep_files: true