name: GPU benchmark and deploy on `main`

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  benchmark:
    uses: lurk-lab/ci-workflows/.github/workflows/bench-deploy.yml@bench-deploy
    with:
      env-prefix: 'LURK'
