name: Test access to secrets

on: 
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
  merge_group:

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  assert-private-key:
    if: github.event_name != 'pull_request' || github.event.action == 'enqueued'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            if ("$PRIVATE_KEY" == "") {
              core.setFailed('Failed to access PRIVATE_KEY secret')
            }
