name: test

on: 
  workflow_dispatch:
  merge_group:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [dev]

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  assert-private-key:
    name: Check private key exists
    runs-on: ubuntu-latest
    steps:
        - uses: actions/github-script@v6
          with:
            script: |
              if [ "$PRIVATE_KEY" == "" ]; then
                core.setFailed('Failed to access PRIVATE_KEY secret')
              fi
