name: 'Test composite action'

on:
  workflow_dispatch:

jobs:
  call-composite-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
          ref: install-deps
      - uses: ./.github/actions/install-deps
        with:
          packages: 'cowsay fortune'
      - run: fortune | cowsay
