name: Custom script

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'GitHub Actions runner'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - buildjet-32vcpu-ubuntu-2204
          - gpu-bench

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  custom-script:
    name: Run local fibonacci bench
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Set up GPU if applicable
        if: github.event.inputs.runner == 'gpu-bench'
        run: |
          nvidia-smi
          nvcc --version
          echo "CUDA_ARCH=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | sed 's/\.//g')" | tee -a $GITHUB_ENV
          echo "EC_GPU_CUDA_NVCC_ARGS=--fatbin --gpu-architecture=sm_${{ env.CUDA_ARCH }} --generate-code=arch=compute_${{ env.CUDA_ARCH }},code=sm_${{ env.CUDA_ARCH }}" | tee -a $GITHUB_ENV
          env | grep -E "LURK|EC_GPU|CUDA"
      # TODO: Remove
      - name: Test env vars
        if: github.event.inputs.runner != 'gpu-bench'
        run: |
          echo "RUNNER_NUM_CPUS=$(nproc --all)" | tee -a $GITHUB_ENV
          echo "RUNNER_TYPE=cpu: ${{ env.RUNNER_NUM_CPUS }} vCPUS" | tee -a $GITHUB_ENV
      - name: Run input script
        run: |
          chmod +x script.sh
          ./script.sh
        working-directory: ${{ github.workspace }}
