name: Custom script

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'GitHub Actions runner'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - buildjet-32vcpu-ubuntu-2204
          - gpu-bench

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  custom-script:
    name: Run local fibonacci bench
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Set up GPU if applicable
        if: github.event.inputs.runner == 'gpu-bench'
        run: |
          nvidia-smi
          nvcc --version
          CUDA_ARCH=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | sed 's/\.//g')
          echo "EC_GPU_CUDA_NVCC_ARGS=--fatbin --gpu-architecture=sm_$CUDA_ARCH --generate-code=arch=compute_$CUDA_ARCH,code=sm_$CUDA_ARCH" | tee -a $GITHUB_ENV
          echo "CUDA_ARCH=$CUDA_ARCH" | tee -a $GITHUB_ENV
          env | grep -E "LURK|EC_GPU|CUDA"
      # TODO: Remove
      - name: Test env vars
        if: github.event.inputs.runner != 'gpu-bench'
        run: |
          TEST_NUM_CPUS=$(nproc --all)
          echo "TEST_NUM_CPUS=$TEST_NUM_CPUS" | tee -a $GITHUB_ENV
      - name: Run input script
        run: |
          chmod +x script.sh
          ./script.sh
        working-directory: ${{ github.workspace }}
