name: Light client benchmark

on:
  workflow_dispatch:
    inputs:
      light-clients:
        description: 'Light clients to benchmark, e.g. `aptos,ethereum`'
        type: string
        required: true

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      light-clients: ${{ steps.set-matrix.outputs.light-clients }}
    steps:
      - name: Convert input to JSON array
        id: set-matrix
        run: |
          light_clients="${{ github.event.inputs.light-clients }}"
          JSON=$(echo "${light-clients}" | jq -Rc 'split(",")')
          echo "light-clients=$JSON" | tee -a "$GITHUB_OUTPUT"

  benchmark:
    name: Light client benchmark
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        light-client: ${{ fromJson(needs.set-matrix.outputs.light-clients) }}
    steps:
      - name: Echo input
        run: |
          echo "Package: ${{ matrix.light-client }}"
