name: PR comment test

on:
  issue_comment:
    types: [created]

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  PR_NUMBER: ${{ github.event.issue.number }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-pr-comment:
    runs-on: ubuntu-latest
    if:
      github.event.issue.pull_request
      && github.event.issue.state == 'open'
      && contains(github.event.comment.body, '!test')
      && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    steps:
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - uses: actions/checkout@v4
      - name: Checkout PR branch
        run: gh pr checkout $PR_NUMBER
      - name: Check private key exists
        uses: actions/github-script@v6
        with:
          script: |
            if ("$PRIVATE_KEY" == "") {
              core.setFailed('Failed to access PRIVATE_KEY secret')
            }
      - name: Comment on successful run
        uses: peter-evans/create-or-update-comment@v3
        with: 
          issue-number: $PR_NUMBER
          body: |
            `!test` action succeeded! :rocket:

            https://github.com/lurk-lab/ci-lab/actions/runs/${{ github.run_id }}
