# Creates a PR benchmark comment with a comparison to master
name: Benchmark pull requests
on:
  issue_comment:
    types: [created]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gpu-benchmark:
    name: run fibonacci benchmark on GPU
    runs-on: [self-hosted, gpu-bench]
    if:
      github.event.issue.pull_request
      && github.event.issue.state == 'open'
      && contains(github.event.comment.body, '!gpu-benchmark')
      && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/gpu-setup
        with:
          gpu-framework: 'cuda'
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Checkout PR branch
        run: gh pr checkout $PR_NUMBER
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.issue.number }}
      # Install dependencies
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        #- run: cargo install critcmp
      - name: Load env vars
        run: |
          echo "LURK_BENCH_OUTPUT=pr-comment" >> $GITHUB_ENV
          echo ${{ github.event.comment.body }} > comment.txt
          BENCHES=$(awk '/Benches:/{f=1;next} /Features:/{f=0} f{print $0}' comment.txt)
          FEATURES=$(awk '/Features:/{f=1;next} /Env vars:/{f=0} f{print $0}' comment.txt)
          ENV_VARS=$(awk '/Env vars:/{f=1;next} /$EOF:/{f=0} f{print $0}' comment.txt)

          echo $BENCHES
          echo $FEATURES
          echo $ENV_VARS

          for var in $ENV_VARS
          do
            echo $var | tee -a $GITHUB_ENV
          done

          echo "BENCHES=$BENCHES" | tee -a $GITHUB_ENV
          echo "FEATURES=$FEATURES" | tee -a $GITHUB_ENV

      # Run the comparative benchmark and comment output on the PR
      - uses: boa-dev/criterion-compare-action@v3
        with:
          # Note: Removing `benchName` causes `criterion` errors: https://github.com/boa-dev/criterion-compare-action#troubleshooting
          # Optional. Compare only this benchmark target
          benchName: ${{ env.BENCHES }}
          # Optional. Features activated in the benchmark
          features: "cuda,${{ env.FEATURES }}"
          # Needed. The name of the branch to compare with
          branchName: ${{ github.ref_name }}
