name: Test calling reusable workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-reusable-test:
    uses: samuelburnham/ci-workflows/.github/workflows/rust-version-check.yml@fix-rust-version-check
