name: Test calling reusable workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-reusable-test:
    uses: lurk-lab/ci-workflows/.github/workflows/lints.yml@install-deps
    with:
      packages: 'cowsay fortune'
