name: Reusable test workflow

on:
  workflow_call:
    inputs:
      left-or-right:
        required: true
        default: true
        type: boolean

jobs:
  left-or-right:
    runs-on: ubuntu-latest
    steps:
    - name: Run the left option
      if: inputs.left-or-right == true
      run: |
        echo 'left'
    - name: Run the right option
      if: inputs.left-or-right == false
      run: |
        echo 'right'
  