name: Merge group tests

on:
  merge_group:
  pull_request:

jobs:
  test-ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print branch names
        if: github.event_name == 'merge_group'
        run: |
            echo "Head ref: ${{ github.event.merge_group.head_ref }}"
            echo "Base ref: ${{ github.event.merge_group.base_ref }}"
            echo "Base ref 2: ${{ github.base_ref }}"
      - uses: actions/checkout@v4
        if: github.event_name == 'merge_group'
        with:
          ref: ${{ github.event.merge_group.base_ref }}
