name: GPU CI

on:
  push:
    branches:
      - gpu-ci

jobs:
  gpu-ci:
    runs-on: gpu-ci
    steps:
      - uses: actions/checkout@v4
      - run: lsb_release -a
      - run: df -h
      - run: nvidia-smi
      - run: sudo apt-get update && sudo apt-get upgrade
      - run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-4
      - run: echo 'PATH=/usr/local/cuda/bin:$PATH' >> $GITHUB_ENV
      - run: nvcc --version
