name: Merge group tests

on:
  merge_group:
  pull_request:

jobs:
  test-ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ github.base_ref }}

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_REF=${{ github.base_ref }}
          elif [[ "${{ github.event_name }}" == "merge_group" ]]; then
            BASE_REF=${{ github.event.merge_group.base_ref }}
            echo $BASE_REF
          fi

          echo "BASE_REF=$BASE_REF" | tee -a $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_REF }}
      - uses: actions/checkout@v4
        with:
          ref: 542679e52a16672768639864b0123074a24aff9f
