name: GPU CI

on:
  push:
    branches:
      - gpu-ci

jobs:
  gpu-ci:
    runs-on: gpu-ci
    steps:
      - uses: actions/checkout@v4
      - run: lsb_release -a
      - name: Test GPU
        run: nvidia-smi
      - run: |
          sudo apt-get update && sudo apt-get upgrade
      - run: |
          wget https://developer.download.nvidia.com/compute/cuda/12.4.0/local_installers/cuda_12.4.0_550.54.14_linux.run
          sudo sh cuda_12.4.0_550.54.14_linux.run
      - run: which nvcc
