on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-rust-toolchain:
    name: Test cargo setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      # Check toolchain version matches latest stable
      # Errors on deprecated `rust-toolchain` file
      # Does nothing if no `rust-toolchain.toml` file
      # Doesn't support setting toolchain via `path` specifier in `rust-toolchain.toml`
      # Only runs once in the currently checked out repo, doesn't do anything for further checkouts?
      # TODO: Place this in a reusable action, either on its own and used in `ci-env` or contained in the latter
      - run: |
          rustup show
          if [ -f "rust-toolchain" ]; then
            echo "Error: `rust-toolchain` file is deprecated. Use `rust-toolchain.toml` instead"
            exit 1
          else if [ -f "rust-toolchain.toml" ]; then
            RUST_TOOLCHAIN=$(grep "channel" rust-toolchain.toml | awk '{ print $3 }')
            if (( $(echo "${{ steps.toolchain.outputs.name }} > $RUST_TOOLCHAIN_FILE" | bc -l) )); then
              echo "Outdated Rust version in `rust-toolchain.toml`"
            fi
          fi
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo bench