name: GPU CI

on:
  push:
    branches:
      - gpu-ci

jobs:
  gpu-ci:
    runs-on: gpu-ci
    steps:
      - uses: actions/checkout@v4
      - run: lsb_release -a
      - name: Test GPU
        run: nvidia-smi
      - run: |
          sudo apt-get update
      - run: |
          sudo apt-get install cuda
      - run: which cuda
