on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-rust-toolchain:
    name: Test cargo setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - run: |
          rustup show
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo bench