name: Custom Warp test

on: 
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: warp-custom-r7iz-metal-16xl
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "I'm a custom Warpbuild runner"
